### PR TITLE
Install Snowflake ODBC

### PR DESCRIPTION
**Pull request by rspada-yesware**
Install the Snowflake ODBC driver into the Heroku build `slug`.

First step is to install the unixodbc driver as it has some files needed for Snowflake ODBC.  Second, install Snowflake ODBC.

The downloads and installs are done from /tmp

### CODE REVIEW

**Comment by mike-yesware** [comment]
Also, I'm not sure if you've seen this, but `heroku run bash` can give you access to a dyno with the buildpack + app code. This can be helpful if trying to look around and validate the results of a build.

**Comment by mike-yesware** [comment]
Also, and also you might be doing this, you can set the buildpack to a branch for rapid iteration while testing, e.g. `https://github.com/heroku/heroku-buildpack-nodejs.git#somedevbranch`

**Comment by rspada-yesware** [comment]
Thanks for the tips!

**Comment by rspada-yesware** [comment]
I thought I'd take a look at the environment from w/in heroku and notice that there isn't a $TMPDIR variable set.  Does it make sense to change the use of $TMPDIR to just /tmp ?

**Pull request merged**
